services:
  db:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_PLUGINS=["apoc"]
      - dbms.directories.import=import
    networks:
      - app
    # volumes:
    #   - neo4j-data:/data
    #   - neo4j-import:/var/lib/neo4j/import

  client:
    container_name: client
    build:
      context: ./client
    stdin_open: true
    ports:
      - '8080:8080'
    networks:
      - app
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  server:
    depends_on:
      db:
        condition: service_started
    command: 
      sh -c 'sleep 15s && npm start'
    container_name: server
    environment:
    - NEO4J_DB:neo4j
    - NEO4J_USERNAME:neo4j
    - NEO4J_PASSWORD:password
    - NEO4J_SCHEME:neo4j
    - NEO4J_HOST:db
    - NEO4J_PORT:7687
    build:
      context: ./server
    ports:
      - '5000:5000'
    networks:
      - app
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

networks:
  app: